spring:
  application:
    name: Test-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.242.94:3306/demo_test?useUnicode=true&characterEncoding=utf8
    username: root
    password: Lichangxin+123
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: false
    open-in-view: true
server:
  port: 8080
mybatis:
  type-aliases-package: com.lcx.domain # resultType 和 parameterType
  mapper-locations:  classpath:mapper/*.xml
